-- ════════════════════════════════════════════════════════════════════
-- 0041_reimbursements.sql
--
-- CLIENT REIMBURSEMENT TRACKER (Project Control).
--
-- The owner/admin (architect) pays a project expense out of personal or
-- company funds; this table records that advance and tracks whether the
-- CLIENT has paid it back. Direction is Client → Owner/Admin. It is NOT an
-- employee reimbursement, and NOT a finance/accounting module.
--
-- DELIBERATELY ISOLATED. A row here is documentation only:
--   · it is never read by any money math (Labor / Material / Overhead /
--     Spent / Earned / Profit all ignore it — see docs/OVERHEAD_MODULE.md),
--   · it creates no invoice, no payment_request, no expense, no payroll row,
--   · status 'reimbursed' is a LABEL, not a transaction.
-- Nothing outside js/reimbursement-module.js may read or write this table;
-- if that ever changes, it stops being a tracker and the isolation rule in
-- CLAUDE.md / docs/ARCHITECTURE.md has to be revisited first.
--
-- Project scope is `folders` (Project Control), NOT construction_projects —
-- those are two different id spaces (docs/ARCHITECTURE.md §3).
--
-- Access: OWNER ONLY. Mirrors folder_budgets_owner (`owner_id = auth.uid()`,
-- which excludes staff, since staff act as their owner through
-- data_owner_id()). Every column here is either a peso amount or context for
-- one, and staff must not see peso amounts. No client-read policy — the MVP
-- has no client-facing surface for this.
--
-- Idempotent — safe on the live DB and on a fresh database.
-- ════════════════════════════════════════════════════════════════════

create table if not exists reimbursements (
  id                uuid primary key default gen_random_uuid(),
  owner_id          uuid not null references auth.users(id) on delete cascade,

  -- Human-readable reference shown in the list: RB-2026-0001. Generated by the
  -- app from the highest sequence already used in that year. Not a key.
  ref_no            text,

  -- Project Control folder the advance was made for.
  folder_id         uuid references folders(id) on delete cascade,
  -- Folder name snapshotted at save time, so a renamed/removed folder still
  -- prints the name the record was created under. Display only.
  project_name      text,

  -- The client who owes the money back (copied from folders.client_email,
  -- editable — the person reimbursing is not always the BOQ contact).
  client_email      text,
  client_name       text,

  -- The owner/admin (architect) who advanced the money.
  paid_by           text,          -- email
  paid_by_name      text,

  expense_category  text,
  description       text,

  amount            numeric not null default 0,   -- amount advanced
  -- Only meaningful for status 'partial' / 'reimbursed'. A running total of
  -- what the client has paid back — still a tracking figure, not a ledger.
  amount_reimbursed numeric not null default 0,

  expense_date      date,          -- when the advance was actually paid out

  receipt_url       text,          -- optional; stored public-format URL in `uploads` (signed on use, 0027)
  receipt_name      text,          -- original filename, display only

  notes             text,          -- free-form note captured on create/edit
  remarks           text,          -- latest status remark (shown in the Remarks column)

  -- pending           → advance recorded
  -- sent_to_client    → reimbursement request sent
  -- partially_reimbursed
  -- reimbursed        → client has fully paid the owner/admin back
  -- cancelled
  status            text not null default 'pending'
                    check (status in ('pending','sent_to_client','partially_reimbursed','reimbursed','cancelled')),

  -- Append-only status/edit trail ([{ at, by, status, from, note }]), same
  -- convention as overhead_expenses.history and labor_contracts.cap_history.
  history           jsonb not null default '[]'::jsonb,

  -- Soft delete. Every read filters `deleted_at is null`. No UI deletes today
  -- (the MVP cancels instead of deleting) — the column keeps that door open
  -- without ever hard-losing a documented advance.
  deleted_at        timestamptz,

  created_by        text,          -- email of the account that recorded it
  created_at        timestamptz default now(),
  updated_at        timestamptz default now()
);

-- Live query is "all rows for this owner, minus the deleted ones".
create index if not exists reimbursements_owner_live_idx
  on reimbursements(owner_id) where deleted_at is null;
create index if not exists reimbursements_folder_idx
  on reimbursements(folder_id) where folder_id is not null;
create index if not exists reimbursements_status_idx on reimbursements(status);
create index if not exists reimbursements_expense_date_idx on reimbursements(expense_date);

alter table reimbursements enable row level security;

-- Owner only — staff are excluded (see header).
drop policy if exists reimbursements_owner on reimbursements;
create policy reimbursements_owner on reimbursements for all
  using (owner_id = auth.uid()) with check (owner_id = auth.uid());

-- Realtime: the module lists records through .onSnapshot(), and a table only
-- broadcasts once it is in the publication — new tables are NOT auto-added
-- (see 0004_realtime.sql). Without this the list would only update on refresh.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'reimbursements'
  ) then
    alter publication supabase_realtime add table public.reimbursements;
  end if;
end $$;
