-- ════════════════════════════════════════════════════════════════════
-- 0043_warranty_retention_fund.sql
--
-- WARRANTY RETENTION REGISTER + FUND (Project Management).
--
-- When a construction project is CLOSED OUT AS COMPLETED, the warranty
-- retention figure the Overview KPI has always shown is frozen into a row
-- here.  Those rows accumulate across projects into a fund, and draws
-- against that fund are recorded in warranty_fund_expenses.
--
-- ── WHAT THE NUMBER IS (read this before trusting it) ────────────────
-- Retention here is DERIVED, not withheld.  js/pm-admin.js computes
--     netCash   = totalPaid - directCost
--     retention = netCash * 5%
-- and nothing is ever held back from a client invoice — the client is
-- billed the full grandTotal (direct cost + management fee).  So a row in
-- this table is an ACCRUED FIGURE, not cash sitting in a bank account.
-- `net_cash_at_closeout`, `total_paid` and `direct_cost` are stored
-- alongside it precisely so the number can always be re-derived and
-- explained later.
--
-- netCash goes NEGATIVE whenever direct costs outran client payments (the
-- Overview already styles that case red).  A negative retention is
-- meaningless as a fund contribution, so `retention_amount` keeps the raw
-- signed value for the record while `contributed_amount` is the clamped
-- max(0, …) figure — and ONLY contributed_amount is ever summed into the
-- pool.
--
-- DELIBERATELY ISOLATED — the same rule as reimbursements (0041).
-- A row in either table is documentation only:
--   · no money math reads it (Labor / Material / Overhead / Spent /
--     Earned / Profit all ignore it — see docs/OVERHEAD_MODULE.md),
--   · it creates no invoice, no payment_request, no expense, no payroll
--     row and no journal entry,
--   · a fund draw does NOT charge any project's Spent.  It has no job to
--     charge: company overhead (G&A) is never charged to a job.
-- Nothing outside js/warranty-fund.js may read or write these tables.  If
-- that ever changes they stop being a register and the isolation rule in
-- CLAUDE.md / docs/ARCHITECTURE.md has to be revisited FIRST.
--
-- Project scope is `construction_projects` (Project Management), NOT
-- `folders` — those are two different id spaces (docs/ARCHITECTURE.md §3).
--
-- Access: OWNER ONLY.  Mirrors reimbursements_owner (`owner_id =
-- auth.uid()`, which excludes staff, since staff act as their owner
-- through data_owner_id()).  Every column is a peso amount or the context
-- for one, and staff must not see peso amounts.  No client-read policy —
-- the client is never shown this.
--
-- Idempotent — safe on the live DB and on a fresh database.
-- ════════════════════════════════════════════════════════════════════


-- ── 1. The register: one row per completed project ──────────────────
create table if not exists warranty_retentions (
  id                   uuid primary key default gen_random_uuid(),
  owner_id             uuid not null references auth.users(id) on delete cascade,

  -- Human-readable reference shown in the list: WR-2026-0001. Generated by
  -- the app from the highest sequence already used in that year. Not a key.
  ref_no               text,

  -- The completed project. construction_projects, NOT folders.
  project_id           uuid references construction_projects(id) on delete set null,
  -- Name/client snapshotted at closeout, so a renamed or removed project
  -- still prints the details the record was created under. Display only.
  project_name         text,
  client_name          text,
  client_email         text,

  -- The closeout row (terminationRequests) that produced this snapshot,
  -- so the register can link back to how the project ended.
  closeout_id          uuid,

  -- ── The frozen arithmetic ──
  -- Stored so the figure stays explainable years later, and so a re-derive
  -- can be checked against what was captured on the day.
  total_paid           numeric not null default 0,   -- cash actually received
  direct_cost          numeric not null default 0,   -- labor + materials + site overhead
  net_cash_at_closeout numeric not null default 0,   -- total_paid - direct_cost
  retention_pct        numeric not null default 5,   -- the rate applied, in percent
  -- Raw signed figure: net_cash_at_closeout * retention_pct/100. May be
  -- NEGATIVE — kept for the record, never summed into the pool.
  retention_amount     numeric not null default 0,
  -- max(0, retention_amount). THIS is the only column the fund totals.
  contributed_amount   numeric not null default 0,

  -- Defects liability period. release_due is stamped by the app at
  -- completed_at + warranty_months so the register can flag what is ripe.
  completed_at         timestamptz,
  warranty_months      integer not null default 12,
  release_due          date,

  -- held     → within the warranty period, notionally set aside
  -- released → warranty period ended clean; the accrual is free
  -- consumed → spent on warranty rectification for this same project
  -- void     → written off / cancelled, contributes nothing
  -- NOTE: superseded by 0044, which simplifies this to active/void and makes
  -- the warranty window a derived value. This file is left as applied.
  status               text not null default 'held'
                       check (status in ('held','released','consumed','void')),
  released_at          timestamptz,
  released_by          text,
  release_note         text,

  notes                text,

  -- Append-only status/edit trail ([{ at, by, status, from, note }]), same
  -- convention as reimbursements.history and overhead_expenses.history.
  history              jsonb not null default '[]'::jsonb,

  -- Soft delete. Every read filters `deleted_at is null`.
  deleted_at           timestamptz,

  created_by           text,
  created_at           timestamptz default now(),
  updated_at           timestamptz default now()
);

-- One register row per project. A project is completed once; re-running a
-- closeout must update the snapshot, not stack a second contribution into
-- the fund. Partial index so the soft-deleted rows don't block a re-entry.
create unique index if not exists warranty_retentions_project_uniq
  on warranty_retentions(project_id) where deleted_at is null and project_id is not null;

create index if not exists warranty_retentions_owner_live_idx
  on warranty_retentions(owner_id) where deleted_at is null;
create index if not exists warranty_retentions_status_idx  on warranty_retentions(status);
create index if not exists warranty_retentions_release_idx on warranty_retentions(release_due);


-- ── 2. Draws against the accumulated fund ───────────────────────────
create table if not exists warranty_fund_expenses (
  id                 uuid primary key default gen_random_uuid(),
  owner_id           uuid not null references auth.users(id) on delete cascade,

  -- WF-2026-0001, same generation scheme as the register above.
  ref_no             text,

  -- Optional: which project's retention this draw is attributed to. NULL
  -- means it is drawn against the general pool. `on delete set null` so
  -- deleting a register row never destroys the record of the spend.
  source_retention_id uuid references warranty_retentions(id) on delete set null,
  -- Snapshotted for display, so the draw still reads correctly if the
  -- register row it pointed at is later removed.
  source_project_name text,

  category           text,
  description        text,
  amount             numeric not null default 0,
  expense_date       date,

  receipt_url        text,   -- optional; public-format URL in `uploads` (signed on use, 0027)
  receipt_name       text,   -- original filename, display only

  notes              text,

  -- recorded  → counted against the fund
  -- cancelled → reversed; excluded from the fund total
  status             text not null default 'recorded'
                     check (status in ('recorded','cancelled')),

  history            jsonb not null default '[]'::jsonb,
  deleted_at         timestamptz,

  created_by         text,
  created_at         timestamptz default now(),
  updated_at         timestamptz default now()
);

create index if not exists warranty_fund_expenses_owner_live_idx
  on warranty_fund_expenses(owner_id) where deleted_at is null;
create index if not exists warranty_fund_expenses_source_idx
  on warranty_fund_expenses(source_retention_id) where source_retention_id is not null;
create index if not exists warranty_fund_expenses_date_idx on warranty_fund_expenses(expense_date);


-- ── 3. RLS — owner only, staff excluded ─────────────────────────────
alter table warranty_retentions    enable row level security;
alter table warranty_fund_expenses enable row level security;

drop policy if exists warranty_retentions_owner on warranty_retentions;
create policy warranty_retentions_owner on warranty_retentions for all
  using (owner_id = auth.uid()) with check (owner_id = auth.uid());

drop policy if exists warranty_fund_expenses_owner on warranty_fund_expenses;
create policy warranty_fund_expenses_owner on warranty_fund_expenses for all
  using (owner_id = auth.uid()) with check (owner_id = auth.uid());


-- ── 4. Realtime ─────────────────────────────────────────────────────
-- The module lists records through .onSnapshot(), and a table only
-- broadcasts once it is in the publication — new tables are NOT auto-added
-- (see 0004_realtime.sql). Without this the list only updates on refresh.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'warranty_retentions'
  ) then
    alter publication supabase_realtime add table public.warranty_retentions;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'warranty_fund_expenses'
  ) then
    alter publication supabase_realtime add table public.warranty_fund_expenses;
  end if;
end $$;
