-- ════════════════════════════════════════════════════════════════════
-- 0045_quotations.sql
--
-- OUTGOING CLIENT QUOTATIONS (Project Estimates).
--
-- A quotation is a SALES document produced BEFORE any project exists.
-- DAC's builds an itemized estimate, prints/exports it, sends it to the
-- prospect, and tracks the outcome (draft → sent → won | lost).
--
-- ── DELIBERATELY ISOLATED — same rule as reimbursements (0041) and the
--    warranty retention fund (0043).  A row here is a PROPOSAL, not
--    revenue:
--      · no money math reads it (Labor / Material / Overhead / Spent /
--        Earned / Profit all ignore it — see docs/OVERHEAD_MODULE.md),
--      · it creates no folder, no construction_project, no invoice, no
--        payment_request, no expense, no payroll row, no journal entry,
--      · marking a quote WON changes a status string and NOTHING else.
--        Converting a won quote into a project is a manual admin action.
--    Nothing outside js/quotation-module.js and js/quotation-print.js may
--    read or write these tables.  If that ever changes they stop being a
--    sales register and the isolation rule in CLAUDE.md /
--    docs/ARCHITECTURE.md has to be revisited FIRST.
--
-- Access: OWNER ONLY.  Mirrors warranty_retentions_owner (`owner_id =
-- auth.uid()`, which excludes staff, since staff act as their owner
-- through data_owner_id()).  Every meaningful column is a peso amount or
-- the context for one, and staff must not see peso amounts.  No
-- client-read policy — the client never sees this inside the system.
--
-- Idempotent — safe on the live DB and on a fresh database.
-- ════════════════════════════════════════════════════════════════════


-- ── 1. The quotation ────────────────────────────────────────────────
create table if not exists quotations (
  id              uuid primary key default gen_random_uuid(),
  owner_id        uuid not null references auth.users(id) on delete cascade,

  -- Q-2026-0001. Generated by the app from the highest sequence already
  -- used that year, and editable. A label, not a key.
  quote_no        text,
  rev_no          integer not null default 1,

  quote_date      date,
  -- Drives the COMPUTED "expired" state. Nothing writes an expired
  -- status; the app derives it (status = 'sent' and valid_until < today).
  valid_until     date,

  client_name     text,
  client_email    text,
  client_address  text,
  client_tin      text,

  project_name    text,
  location        text,
  subject         text,
  scope_note      text,

  -- The 3-level tree: [{ id, label, pricing, lumpAmount, images:[],
  --   groups:[{ id, label, lumpAmount, lines:[{ id, description, qty,
  --   unit, unitPrice, state }] }] }]
  -- ONE client-facing rate per line. There is deliberately NO
  -- material/labor split here — that is internal costing and belongs in
  -- the BOQ, never on a document a client reads.
  sections        jsonb not null default '[]'::jsonb,

  discount        numeric not null default 0,
  discount_type   text    not null default 'amount'
                  check (discount_type in ('amount','percent')),

  -- none      → sheet prints "VAT not applicable"
  -- exclusive → VAT computed at vat_pct and ADDED to the sub-total
  -- inclusive → total unchanged; the VAT component is shown broken out
  vat_mode        text    not null default 'none'
                  check (vat_mode in ('none','exclusive','inclusive')),
  vat_pct         numeric not null default 12,

  -- Final total after discount and VAT. Denormalised for list sorting and
  -- pipeline stats; recomputed by the app on every save.
  total_amount    numeric not null default 0,

  status          text not null default 'draft'
                  check (status in ('draft','sent','won','lost')),
  status_note     text,
  -- Stamped when status moves to won/lost, cleared if it moves back.
  -- Powers win-rate-over-time without scanning the history blob.
  decided_at      timestamptz,

  -- In-app reminder only. NOTHING is emailed from these columns.
  follow_up_date  date,
  follow_up_note  text,

  -- { validityNote, payment, deliveryTimeline, warranty, exclusions,
  --   conditions:[{title,body,include}], signOff:{preparedBy,clientApproval} }
  terms           jsonb not null default '{}'::jsonb,
  prepared_by     text,

  -- Append-only status/edit trail ([{ at, by, status, from, note }]),
  -- same convention as reimbursements.history.
  history         jsonb not null default '[]'::jsonb,

  -- Soft delete. Every read filters `deleted_at is null`.
  deleted_at      timestamptz,

  created_by      text,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

create index if not exists quotations_owner_live_idx
  on quotations(owner_id) where deleted_at is null;
create index if not exists quotations_status_idx     on quotations(status);
create index if not exists quotations_date_idx       on quotations(quote_date);
create index if not exists quotations_valid_idx      on quotations(valid_until);
create index if not exists quotations_followup_idx
  on quotations(follow_up_date) where follow_up_date is not null;


-- ── 2. Immutable revision snapshots ─────────────────────────────────
-- Every SEND freezes a full copy. The module only ever INSERTs here;
-- there is no edit or delete path. Rows disappear only with the parent.
--
-- Storage trade-off, made knowingly: a quote revised eight times stores
-- its tree eight times. At this volume (hundreds of quotes) that is cheap,
-- and it makes any revision printable on its own. Storing diffs instead
-- would halve the storage and double the complexity.
create table if not exists quotation_revisions (
  id            uuid primary key default gen_random_uuid(),
  quotation_id  uuid not null references quotations(id) on delete cascade,
  -- Denormalised so the RLS check stays single-table.
  owner_id      uuid not null references auth.users(id) on delete cascade,

  rev_no        integer not null,
  snapshot      jsonb   not null,
  total_amount  numeric not null default 0,
  sent_at       timestamptz,
  note          text,
  created_at    timestamptz default now()
);

create unique index if not exists quotation_revisions_uniq
  on quotation_revisions(quotation_id, rev_no);
create index if not exists quotation_revisions_owner_idx
  on quotation_revisions(owner_id);


-- ── 3. Reusable client blocks and scope blocks ──────────────────────
create table if not exists quotation_presets (
  id          uuid primary key default gen_random_uuid(),
  owner_id    uuid not null references auth.users(id) on delete cascade,

  -- 'client' → data is a client block { clientName, clientEmail,
  --            clientAddress, clientTin }
  -- 'scope'  → data is { sections: [ …same shape as quotations.sections ] }
  kind        text not null check (kind in ('client','scope')),
  name        text not null,
  data        jsonb not null default '{}'::jsonb,

  deleted_at  timestamptz,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

create index if not exists quotation_presets_owner_kind_idx
  on quotation_presets(owner_id, kind) where deleted_at is null;


-- ── 4. RLS — owner only, staff excluded ─────────────────────────────
alter table quotations          enable row level security;
alter table quotation_revisions enable row level security;
alter table quotation_presets   enable row level security;

drop policy if exists quotations_owner on quotations;
create policy quotations_owner on quotations for all
  using (owner_id = auth.uid()) with check (owner_id = auth.uid());

drop policy if exists quotation_revisions_owner on quotation_revisions;
create policy quotation_revisions_owner on quotation_revisions for all
  using (owner_id = auth.uid()) with check (owner_id = auth.uid());

drop policy if exists quotation_presets_owner on quotation_presets;
create policy quotation_presets_owner on quotation_presets for all
  using (owner_id = auth.uid()) with check (owner_id = auth.uid());


-- ── 5. Realtime ─────────────────────────────────────────────────────
-- The module lists through .onSnapshot(), and a table only broadcasts
-- once it is in the publication — new tables are NOT auto-added (see
-- 0004_realtime.sql). Without this the list only updates on refresh.
do $$
declare t text;
begin
  foreach t in array array['quotations','quotation_revisions','quotation_presets']
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;
