import React from 'react';
import {Badge,Button,Card,Field,Heading,Icon,Note,Row,Stats,Progress,Building,C} from './ui';
export function PhoneContent({id,p}:{id:string;p:number}){
 const changed=p>=1,done=p>=2;
 switch(id){
 case 'W01':case 'W02':case 'W12':return <><Heading sub="Villanueva Residence">Magandang umaga, Juan.</Heading><Card active><Badge>Today on site</Badge><div style={{fontSize:48,fontWeight:800,margin:'18px 0'}}>07:30 <span style={{fontSize:20,color:C.muted}}>AM</span></div><Button>{changed?'Working on site':'Time In'}</Button></Card><Row title="My requests" sub="2 updates from the office" right={<Badge>2</Badge>}/><Row title="My Work" sub="Electrical preparation · Today" icon="note" active={done}/><Row title="Juan Santos" sub="Worker · Site Team A" icon="person"/></>;
 case 'W03':return <><Heading sub="Keep your day on record">{done?'Attendance history':changed?'Review Time In':'Time In'}</Heading>{done?<><Note>Time Out recorded · 4:30 PM</Note><Row title="30 Sep · Complete" sub="7:30 AM – 4:30 PM" icon="clock"/><Row title="29 Sep · Complete" sub="7:32 AM – 4:31 PM" icon="clock"/></>:<><Field label="Attendance-enabled site" value="Villanueva Residence" active/><Building height={175}/><div style={{height:14}}/><Row title={changed?'Photo attached':'Take your photo'} sub="Confirm your site and photo" icon="camera" active/><Button>{changed?'Submit Time In':'Continue'}</Button></>}</>;
 case 'W04':return <><Heading sub="Materials + tools">New request</Heading><Field label="Project" value="Villanueva Residence"/><Field label="Work scope" value="Main Contract"/><Row title="THHN wire" sub="3.5 mm² · 1 roll" active={changed}/><Row title="Cordless drill" sub="Reusable tool · 1 unit" icon="tool"/><Button>{done?'Request submitted':'Review request'}</Button></>;
 case 'W05':return <><Heading sub="Can’t find the item?">Add unlisted item</Heading><Field label="Description" value="Weatherproof junction box" active/><Building height={128}/><Row title="Reference photo" sub="Attached to this request" icon="camera"/><Card active={changed}><div style={{display:'flex',justifyContent:'space-between',fontSize:23,fontWeight:700}}>Urgent item<Badge tone={changed?'amber':'muted'}>{changed?'On':'Off'}</Badge></div><div style={{fontSize:17,color:C.muted,marginTop:12}}>Only this line is marked urgent.</div></Card><Button>{done?'Item added':'Add to request'}</Button></>;
 case 'W06':return <><Heading sub="Team leader · Mark">Team request</Heading><Field label="Assigned team" value="Electrical Team A"/><Row title="Duplex outlet" sub="Same specification · pieces"/><Stats items={changed?[['10','Arranged'],['2','Next batch']]:[['10','Requested'],['0','Additional']]}/><Note>{changed?'Extra 2 are separate from the arranged 10.':'Team needs in one combined request.'}</Note><Button>{done?'Changes saved':'Update quantity'}</Button></>;
 case 'W07':return <><Heading sub="Your changes stay visible">Request sync</Heading><Badge tone={changed?'green':'amber'}>{changed?'Back online':'No signal'}</Badge><div style={{height:25}}/><Card><div style={{fontSize:26,fontWeight:700}}>PVC elbow · ½ inch</div><div style={{fontSize:52,fontWeight:800,margin:'14px 0'}}>8 pcs</div><Badge tone="amber">{changed?'Needs review':'Pending sync'}</Badge></Card>{changed?<><Note amber>The office updated this item to 12 pcs.</Note><Button>Review both changes</Button></>:<Note>Saved on this phone. Not yet accepted by the office.</Note>}</>;
 case 'W08':return <><Heading sub="Authorized project references">Find Previous Item</Heading><Field label="Search by name or specification" value="Duplex outlet" active/><Building height={140}/><Row title="Duplex outlet" sub="16A · white · 2-gang" active={changed}/><Badge tone="muted">Historical reference</Badge><div style={{height:20}}/><Button>{done?'New draft created':'Request this item again'}</Button></>;
 case 'W09':return <><Heading sub="Today · Electrical Team A">My Work</Heading><Card active><Badge>Today</Badge><div style={{fontSize:28,fontWeight:800,margin:'15px 0'}}>Prepare electrical lines</div><div style={{fontSize:20,lineHeight:1.4}}>Responsible: Juan Santos<br/>Helper: Ben Cruz<br/>Project: Villanueva Residence</div></Card><Note>Check materials and wall preparation before starting.</Note><Button>{changed?'Acknowledged':'I’ve read this'}</Button><div style={{height:16}}/><Row title="Shared meeting notes" sub="Published version · 30 Sep" icon="note" active={done}/></>;
 case 'W10':return <><Heading sub="Prepare electrical lines">Work status</Heading><Card active><Badge tone={done?'green':'amber'}>{done?'Awaiting office verification':changed?'Blocker reported':'In progress'}</Badge><div style={{fontSize:27,fontWeight:800,margin:'17px 0'}}>{done?'Work reported done':'Missing materials'}</div><div style={{fontSize:20,lineHeight:1.45}}>{done?'Leader check is recorded. Final verification is with the office.':'Conduit and wire are needed before work can continue.'}</div></Card><Button>{done?'View work history':changed?'View blocker report':'Report a problem'}</Button><div style={{height:18}}/><Note>{done?'Reported done ≠ Completed':'A blocker does not create a purchase.'}</Note></>;
 case 'W11':return <><Heading sub="Assigned responsibility">My Tools</Heading><div style={{height:110,display:'grid',placeItems:'center',color:C.green}}><Icon name="tool" size={90}/></div><Row title="Cordless drill" sub="Asset TL-024 · Good condition" icon="tool" active/><Field label="Responsible person" value="Juan Santos"/><Field label="Current location" value="Villanueva Residence"/><Badge>{changed?'Handover recorded':'Assigned to you'}</Badge><div style={{height:20}}/><Button>{done?'Return condition recorded':'View handover / return'}</Button></>;
 case 'B01':case 'B02':case 'B12':return <><Heading sub="Procurement · Liza Reyes">Buying list</Heading><div style={{display:'flex',gap:8,marginBottom:20}}><Badge>This batch</Badge><Badge tone="muted">By project</Badge></div><Row title="THHN wire" sub="Villanueva · 1 roll" right={<Badge tone="amber">Urgent</Badge>} active={changed}/><Row title="Duplex outlet" sub="Villanueva · 10 pcs" right={<Badge>Assigned</Badge>}/><Row title="PVC pipe" sub="Santos Townhouse · 6 pcs"/><Note>{done?'Quantity changes stay visible.':'Review project, specification and priority.'}</Note></>;
 case 'B03':return <><Heading sub="Claim an available portion">Who’s buying?</Heading><Row title="THHN wire" sub="3.5 mm² · 1 roll" active/><Field label="Buyer" value={changed?'Liza Reyes':'Unassigned'}/><Badge>{changed?'Claim confirmed online':'Online'}</Badge><div style={{height:22}}/><Button>{changed?'Assigned to you':'I’ll buy this'}</Button><div style={{height:20}}/><Note>Other authorized buyers can see the assignment.</Note></>;
 case 'B04':return <><Heading sub="Actual purchase details">Record purchase</Heading><Field label="Item / specification" value="Duplex outlet · 16A"/><div style={{display:'flex',gap:12}}><div style={{flex:1}}><Field label="Quantity" value="6 pcs" active/></div><div style={{flex:1}}><Field label="Amount" value="••••"/></div></div><Field label="Supplier" value="Sample Hardware"/><Row title="Receipt attached" sub="30 Sep · SI-0104" icon="note"/><Button>{done?'Purchase recorded':'Save purchase'}</Button></>;
 case 'B05':return <><Heading sub="Duplex outlet · 16A">Partial buying</Heading><Stats items={changed?[['6','Bought'],['4','Still to buy']]:[['0','Bought'],['10','Still to buy']]}/><Card><div style={{fontSize:21}}>Needed <b style={{float:'right'}}>10 pcs</b></div><Progress value={changed?60:0}/><div style={{fontSize:20,color:C.muted}}>Assigned buyer: Liza Reyes</div></Card><Note>{done?'The remaining 4 can be released explicitly.':'Unbought quantities stay assigned to you.'}</Note><Button>{done?'Release remaining 4':'Record purchase of 6'}</Button></>;
 case 'B06':return <><Heading sub="One receipt · SI-0104">Project allocations</Heading><Card><div style={{fontFamily:'Mono',fontSize:19,letterSpacing:2,borderBottom:`1px dashed ${C.line}`,paddingBottom:18,marginBottom:18}}>SAMPLE HARDWARE</div><Row title="Duplex outlet · 6 pcs" sub="Villanueva · Main Contract" active={changed}/><Row title="PVC pipe · 6 pcs" sub="Santos · Additional Works"/><div style={{fontSize:19,color:C.muted}}>Receipt total <b style={{float:'right'}}>••••</b></div></Card><Note>One purchase. Item-level destinations.</Note><Button>{done?'Allocation saved':'Review item links'}</Button></>;
 case 'B07':return <><Heading sub="Keep the original request">Substitute item</Heading><Field label="Requested" value="Duplex outlet · Brand A"/><Field label="Actually bought" value={changed?'Duplex outlet · Brand B':'Select replacement'} active/><Field label="Reason" value="Requested brand unavailable"/><Note>Specification and unit remain visible.</Note><Button>{done?'Substitute recorded':'Save with reason'}</Button><div style={{height:16}}/><Badge tone="muted">Unplanned purchase also needs a reason.</Badge></>;
 case 'B08':return <><Heading sub="Purchase P-0104">Payment details</Heading><Card active><Badge tone={changed?'green':'amber'}>{changed?'Paid':'Unpaid'}</Badge><div style={{fontSize:29,fontWeight:800,margin:'20px 0'}}>Sample Hardware</div><Field label="Payment amount" value="••••"/><Field label="Actual payment date" value="30 September 2026"/><Field label="Method" value="Bank transfer"/></Card><Note>Same purchase. No second material expense.</Note><Button>{done?'Payment recorded':'Save payment'}</Button></>;
 case 'B09':return <><Heading sub="Confirm the actual delivery">Receive at site</Heading><Field label="Location" value="Villanueva Residence"/><Field label="Received quantity" value={changed?'6 pcs':'Enter quantity'} active/><Field label="Condition" value={changed?'Usable · Checked':'Check actual condition'}/><Note>{done?'Confirmed usable stock: +6 pcs':'A receipt photo alone does not add stock.'}</Note><Button>{done?'Receiving confirmed':'Confirm received online'}</Button></>;
 case 'B10':return <><Heading sub="Purchase draft · saved locally">Pending sync</Heading><Badge tone="amber">{changed?'Assignment changed':'No signal'}</Badge><div style={{height:22}}/><Row title="Receipt SI-0104" sub="Photo and details kept" icon="note"/><Card><div style={{fontSize:24,fontWeight:700}}>Duplex outlet · 6 pcs</div><div style={{fontSize:19,color:C.muted,marginTop:12}}>Shared Bought total is unchanged.</div></Card><Note amber>{changed?'The office reassigned this portion. Review the draft before acceptance.':'Draft remains on this phone until accepted.'}</Note><Button>{changed?'Resolve assignment change':'View saved draft'}</Button></>;
 case 'B11':return <><Heading sub="Confirmed stock by location">Inventory</Heading><Stats items={[[changed?'24':'18','Warehouse'],['6','Villanueva']]}/><Row title="Receipt" sub="Confirmed usable quantities" icon="check" active={changed}/><Row title="Issue / transfer" sub="Move with a clear record" icon="arrow"/><Row title="Return" sub="Check quantity and condition" icon="box"/><Note>Reservations and stock balances have separate states.</Note></>;
 default:throw new Error(`Unknown phone scene ${id}`);
 }
}
