import React from 'react';
import {Badge,Button,Card,Field,Heading,Icon,Note,Row,Stats,Progress,Building,Flow,Table,C} from './ui';
const Split=({left,right}:{left:React.ReactNode;right:React.ReactNode})=><div style={{display:'grid',gridTemplateColumns:'1.15fr 1fr',gap:24}}><div>{left}</div><div>{right}</div></div>;
const PanelTitle=({children}:{children:React.ReactNode})=><div style={{fontFamily:'Georgia,serif',fontSize:34,fontWeight:600,marginBottom:22}}>{children}</div>;
export function WebContent({id,p}:{id:string;p:number}){
 const a=p>=1,b=p>=2;
 switch(id){
 case 'D01':case 'D20':return <><PanelTitle>Your office, connected.</PanelTitle><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:18}}>{[['Project Control','Monitoring · Billing · Reports','home'],['Project Management','Projects · Site operations','box'],['Attendance','Workers · Time In / Out','clock'],['Quotations','Estimates & proposals','note'],['Construction','Materials & orders','cart'],['Users','People & access','person']].map(([t,s,icon],i)=><Card key={t} active={i===p} style={{padding:24,margin:0}}><Icon name={icon} size={35}/><div style={{fontSize:26,fontWeight:700,margin:'16px 0 9px'}}>{t}</div><div style={{color:C.muted,fontSize:18}}>{s}</div></Card>)}</div><div style={{marginTop:20}}><Note>Sample workspace · Access depends on role and allowed modules.</Note></div></>;
 case 'D02':return <><PanelTitle>Users · Navigator</PanelTitle><Split left={<><Row title="Owner" sub="Company overview and restricted modules" icon="person" active={!a}/><Row title="Office staff" sub="Assigned modules and permitted records" icon="person" active={a}/><Row title="Worker / team leader" sub="WorkMate role-specific workspace" icon="person"/></>} right={<Card><Heading sub="Example account permissions">{a?'Limited staff view':'Owner view'}</Heading><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><Badge>Attendance</Badge><Badge>Construction</Badge>{!a&&<><Badge>Financial reports</Badge><Badge>Warranty Fund</Badge></>}</div><div style={{height:28}}/><Note>{a?'Peso amounts and restricted controls are hidden.':'Owner-only modules are explicitly restricted.'}</Note></Card>}/></>;
 case 'D03':return <><PanelTitle>Project Control · Overview</PanelTitle><Stats items={[[a?'50%':'48%','Accomplishment'],['₱400,000','Spent'],['₱100,000','Earned profit']]}/><Split left={<><Row title="Villanueva Residence" sub="Main Contract · Active" icon="home" active/><Row title="Additional Works 01" sub="Electrical additions · Linked scope"/><Row title="Billing periods" sub="Fund allocations and expense records" icon="note"/></>} right={<Card><Building height={190}/><div style={{fontSize:23,fontWeight:700,marginTop:18}}>Project cost and progress</div><Progress value={a?50:48}/><Badge>Owner view · sample figures</Badge></Card>}/></>;
 case 'D04':return <><PanelTitle>Project costs & allocation planning</PanelTitle><Stats items={[["₱150,000","Labor"],["₱200,000","Material"],["₱50,000","Overhead"],["₱400,000","Spent"]]}/><Split left={<Card><Heading sub="A peso belongs in one cost bucket">Actual costs</Heading>{[['Labor',37.5],['Material',50],['Overhead',12.5]].map(([label,v])=><div key={label}><div style={{fontSize:20}}>{label}</div><Progress value={Number(v)}/></div>)}</Card>} right={<Card active={a}><Heading sub="Budget envelopes · planning only">Billing allocation</Heading><Flow steps={['70% Direct','20% Indirect','10% Target reserve']} active={p}/><div style={{height:20}}/><Note>Planned envelopes do not add revenue, cost or profit.</Note></Card>}/></>;
 case 'D05':return <><PanelTitle>Expenses & pakyaw contracts</PanelTitle><Table headers={['Record','Reference','Treatment']} rows={[["Direct labor","LC-021","Pakyaw contract"],["Materials","SI-0104","Project cost"],["Cover expense","Company-funded","Included in Spent"]]} highlight={p}/><div style={{marginTop:24}}><Split left={<Note>Cover ₱20,000 is a subset of Spent ₱400,000.</Note>} right={<Note>Overhead pay does not draw down the pakyaw contract.</Note>}/></div></>;
 case 'D06':return <><PanelTitle>Accomplishment · BOQ</PanelTitle><Split left={<Table headers={['Work item','Completion']} rows={[["Foundation","100%"],["Wall works",a?'75%':'65%'],["Electrical","25%"]]} highlight={a?1:0}/>} right={<><Card active><Badge>Earned</Badge><div style={{fontSize:48,fontWeight:800,margin:'15px 0'}}>₱500,000</div><div style={{fontSize:22}}>50% complete × ₱1,000,000 contract</div></Card><Note>Without accomplishment data, the estimate is labelled Forecast.</Note><Badge tone="muted">Owner view · sample figures</Badge></>}/></>;
 case 'D07':return <><PanelTitle>Invoices & payment requests</PanelTitle><Table headers={['Document','Project','Status']} rows={[["Sales invoice INV-104","Villanueva",a?'Issued':'Draft'],["Labor invoice LI-021","Villanueva","For review"],["Payment request PR-013","Santos",b?'Verified':'Pending verification']]} highlight={p}/><div style={{marginTop:26}}><Flow steps={['Review records','Print / export','Verify payment']} active={p}/></div><div style={{marginTop:18}}><Badge tone="muted">Exports depend on the selected module.</Badge></div></>;
 case 'D08':return <><PanelTitle>Overhead & reimbursements</PanelTitle><Split left={<Card><Heading sub="Company-level general expenses">Company overhead</Heading><Row title="Office expenses" sub="Kept separate from job costs" icon="home"/><Note>G&A is not charged to a project.</Note></Card>} right={<Card active={a}><Heading sub="Owner-only tracking register">Client reimbursement</Heading><Table headers={['Advance','Status']} rows={[["Sample record RB-014",a?'Paid back':'Awaiting reimbursement']]}/><div style={{height:22}}/><Note>No automatic invoice, payment or expense entry.</Note></Card>}/></>;
 case 'D09':return <><PanelTitle>Project Management · Projects</PanelTitle><Badge tone="muted">Separate from Project Control</Badge><div style={{height:22}}/><Split left={<><Row title="Santos Build" sub="Daily expense records and weekly bills" icon="home" active/><Row title="Procurement" sub="Requests and site requirements" icon="cart"/><Row title="Milestones" sub="Work progress and target dates" icon="check" active={a}/></>} right={<Card><Heading sub="Project Management workflow">Site operations</Heading><Flow steps={['Daily records','Weekly billing','Progress review']} active={p}/><div style={{height:25}}/><Building height={145}/></Card>}/></>;
 case 'D10':return <><PanelTitle>Site operations & supporting records</PanelTitle><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:18}}>{[['Daily logs','Daily activity and site updates','note'],['Walkthroughs','Observations and follow-up items','search'],['Accomplishment reports','Supporting progress documentation','check'],['Revolving fund','Fund movements and records','box']].map(([t,s,i],n)=><Card key={t} active={n===p} style={{margin:0}}><Icon name={i}/><div style={{fontSize:28,fontWeight:700,margin:'15px 0 8px'}}>{t}</div><div style={{fontSize:20,color:C.muted}}>{s}</div></Card>)}</div></>;
 case 'D11':return <><PanelTitle>Project Closeout & Warranty Fund</PanelTitle><Split left={<Card active><Heading sub="Owner review">Closeout record</Heading><Field label="Project status" value={a?'Completed':'For closeout review'}/><Flow steps={['Review costs','Final bill','Closeout']} active={p}/><div style={{height:20}}/><Badge tone="muted">Terminated = stopped before completion</Badge></Card>} right={<Card><Heading sub="Internal company reserve">Warranty Fund</Heading><Row title="Contribution register" sub="Frozen on completion" icon="note"/><Row title="Fund expenses" sub="Draws from the company reserve" icon="box"/><Note>Not a deduction from client billing.</Note></Card>}/></>;
 case 'D12':return <><PanelTitle>Quotations · estimates & proposals</PanelTitle><Table headers={['Quotation','Revision','Status']} rows={[["Q-104 · Sample residence","Rev 2",b?'Won':a?'Sent':'Draft'],["Q-105 · Fit-out proposal","Rev 1","Draft"]]} highlight={0}/><div style={{height:30}}/><Flow steps={['Itemized estimate','Revise & send','Track outcome']} active={p}/><div style={{height:20}}/><Note>A Won quotation stays a proposal record. Project creation is a separate admin action.</Note></>;
 case 'D13':return <><PanelTitle>Attendance · Today on site</PanelTitle><div style={{display:'flex',gap:10,marginBottom:22}}>{['Today on site','Workers','Sites & schedule','Hours report'].map((x,i)=><Badge key={x} tone={i===p?'green':'muted'}>{x}</Badge>)}</div><Table headers={['Worker','Site','Time In','Status']} rows={[["Juan Santos","Villanueva","07:30 AM",b?'Complete':'Working'],["Ben Cruz","Villanueva","07:32 AM","Working"],["Sample worker","Santos","—","No record"]]} highlight={p}/><div style={{display:'flex',gap:14,marginTop:24}}><Badge>Photo and record review</Badge><Badge tone="muted">Hours report ≠ payroll calculation</Badge><Badge tone="muted">App updates · owner</Badge></div></>;
 case 'D14':return <><PanelTitle>Construction & Expense Inbox</PanelTitle><Split left={<><Row title="Current Batch" sub="Requests grouped for processing" icon="box" active={!a}/><Row title="Urgent Requests" sub="Items needing attention" icon="alert"/><Row title="Batch History & Inventory" sub="Past batches and stock records"/></>} right={<Card active={a}><Heading sub="Receipt photos awaiting encoding">Expense Inbox</Heading><Row title="Sample receipt photo" sub="Project Control · tagged to job" icon="camera"/><Badge tone="amber">Awaiting encoding</Badge><div style={{height:20}}/><Button>{b?'Ready for review':'Open receipt inbox'}</Button></Card>}/></>;
 case 'D15':return <><PanelTitle>WorkMate · office request queue</PanelTitle><Table headers={['Request','Item / team','Next action']} rows={[["R-1043 · Villanueva","Unlisted junction box",a?'Catalogue matched':'Match item'],["R-1044 · Santos","Electrical Team A","Review schedule"],["R-1045 · Villanueva","Additional 2 outlets",b?'Next batch':'Review quantity']]} highlight={p}/><div style={{height:24}}/><Flow steps={['Review requests','Match & schedule','Update requester']} active={p}/><div style={{marginTop:18}}><Badge tone="muted">Later: item history · tools · owner cost review</Badge></div></>;
 case 'D16':return <><PanelTitle>Meetings & Work Plan</PanelTitle><Split left={<Card><Heading sub="Typed or pasted meeting notes">Draft tasks</Heading><div style={{fontSize:24,lineHeight:1.5,background:'#F5F5EF',padding:20,borderRadius:12,marginBottom:20}}>Start ng wiring sa Monday. Kailangan muna ang conduit at wall preparation.</div><Badge tone="amber">Clarify exact date and recipients</Badge><div style={{height:18}}/><Button>{a?'Review draft tasks':'Draft with AI / manually'}</Button></Card>} right={<><Flow steps={['Draft','Staff review','Publish']} active={p}/><div style={{height:20}}/><Row title={b?'Published task':'Prepare electrical lines'} sub={b?'Acknowledgements and blockers visible':'Staff checks names, dates and recipients'} icon="note" active/><Note>Reported done still needs final office verification.</Note></>}/></>;
 case 'D17':return <><PanelTitle>Client & partner portals</PanelTitle><div style={{display:'flex',gap:18}}>{[['Design client','BOQ and design-side project records'],['Construction client','Construction project experience'],['Partner','Partnership project experience']].map(([t,s],i)=><Card key={t} active={i===p} style={{flex:1}}><Building height={125}/><div style={{fontFamily:'Georgia,serif',fontSize:27,margin:'17px 0'}}>{t}</div><div style={{fontSize:21,lineHeight:1.35,color:C.muted}}>{s}</div><div style={{height:20}}/><Badge>Scoped access</Badge></Card>)}</div><Note>Each audience sees only the records available to their account.</Note></>;
 case 'D18':return <><PanelTitle>Appointments, analytics & feedback</PanelTitle><Split left={<Table headers={['Inquiry','Schedule','Status']} rows={[["Design consultation","01 Oct · 10 AM",a?'Confirmed':'Requested'],["Project discussion","02 Oct · 2 PM","For review"]]} highlight={0}/>} right={<><Row title="Analytics" sub="Review inquiry and appointment activity" icon="note" active={a}/><Row title="Client feedback" sub="Review submitted experiences" icon="person" active={b}/><Building height={140}/></>}/></>;
 case 'D19':return <><PanelTitle>Reports & review tools</PanelTitle><Split left={<><Row title="Reports" sub="Project records and available exports" icon="note" active={!a}/><Row title="AI-assisted summaries" sub="Briefings for review" icon="search" active={a}/><Row title="System Errors" sub="Owner-only reported issues" icon="alert" active={b}/></>} right={<Card><Heading sub="Evidence supports the review">Keep records traceable</Heading><Flow steps={['Source records','Review findings','Follow up']} active={p}/><div style={{height:25}}/><Note>AI summaries support review; verify important details against source records.</Note></Card>}/></>;
 default:throw new Error(`Unknown Web scene ${id}`);
 }
}
